### ISSUE TITLE
1.6.x branch failed being created

### ISSUE THREAD

**Issue by Ocramius** [laminas-api-tools/api-tools-api-problem#22]
### Bug Report

See https://github.com/laminas-api-tools/api-tools-api-problem/actions/runs/1558155992

We'll need to do some manual steps:

 * create 1.6.x
 * check release notes
 * create 1.6.0 milestone

**Comment by weierophinney** [comment]
I've:

- Created the 1.6.x branch and made it the default branch
- Created the 1.5.x milestone (the 1.6.0 milestone already exists)
- Created the 1.5.0 release from the 1.5.0 tag

**Comment by Ocramius** [comment]
Thank you, @weierophinney!
