### ISSUE TITLE
API Problem translation based on Accept-Language?

### ISSUE THREAD

**Issue by weierophinney** [laminas-api-tools/api-tools-api-problem#3]
I was wondering, would it make sense for apigiliy and api-problem in general to support a translator service, so as to translate all messages in the ApiProblem response based on the Accept-Language HTTP header?

This way in theory a multilingual rest client could get different error messages per language set in the request.

What do you think is the best way to go about it? 

---

Originally posted by @twmobius at https://github.com/zfcampus/zf-api-problem/issues/40

**Comment by FXLima** [comment]
I'm using https://docs.laminas.dev/laminas-i18n/translation/
I capture Accept-Language in the HTTP header and go through the Translate routines.

**Comment by Ocramius** [comment]
Closing here, IMO answered perfectly by @FXLima
